export interface AppletSettings {
    INCLUDE_DIMENSION: boolean;
    INCLUDE_PROFIT_CENTER: boolean;
    INCLUDE_PROJECT: boolean;
    INCLUDE_SEGMENT: boolean;
    INCLUDE_SST: boolean;
    INCLUDE_WHT: boolean;
    DEFAULT_BRANCH: string;
    DEFAULT_LOCATION: string;
    DEFAULT_DELIVERY_BRANCH: string;
    DEFAULT_DELIVERY_LOCATION: string;
    DEFAULT_COMPANY: string;
    DEFAULT_TOGGLE_COLUMN: string;
    ENABLE_DIMENSION: boolean;
    ENABLE_PROFIT_CENTER: boolean;
    ENABLE_PROJECT: boolean;
    ENABLE_SEGMENT: boolean;
    ENABLE_SST: boolean;
    ENABLE_WHT: boolean;
    PRINTABLE: string;
    ENABLE_CUSTOM_STATUS_1: boolean;
    ENABLE_CUSTOM_STATUS_2: boolean;
    ENABLE_CUSTOM_STATUS_3: boolean;
    ENABLE_CUSTOM_STATUS_4: boolean;
    ENABLE_CUSTOM_STATUS_5: boolean;
    EDIT_CONTRA_TXN_DATE: boolean;
    ENABLE_CUSTOM_STATUS_HDR_1: boolean;
    ENABLE_CUSTOM_STATUS_HDR_2: boolean;
    ENABLE_CUSTOM_STATUS_HDR_3: boolean;
    ENABLE_CUSTOM_STATUS_HDR_4: boolean;
    ENABLE_CUSTOM_STATUS_HDR_5: boolean;
    ENABLE_CUSTOM_STATUS_LINE_1: boolean;
    ENABLE_CUSTOM_STATUS_LINE_2: boolean;
    ENABLE_CUSTOM_STATUS_LINE_3: boolean;
    ENABLE_CUSTOM_STATUS_LINE_4: boolean;
    ENABLE_CUSTOM_STATUS_LINE_5: boolean;
    HIDE_TRACKING_ID: boolean;
    HIDE_PERMIT_NO: boolean;

    HIDE_UNIT_PRICE_STD_PRICING_SCHEME: boolean;
    HIDE_UNIT_PRICE_STD_INCL_TAX: boolean;
    HIDE_UNIT_PRICE_STD_EXCL_TAX: boolean;
    HIDE_UNIT_PRICE_STD_UOM_INCL_TAX: boolean;
    HIDE_UNIT_PRICE_STD_UOM_EXCL_TAX: boolean;
    HIDE_UNIT_PRICE_NET_UOM_EXCL_TAX: boolean;
    HIDE_UNIT_PRICE_NET_EXCL_TAX: boolean;
    HIDE_UNIT_DISCOUNT: boolean;
    HIDE_QTY_BASE: boolean;
    HIDE_QTY_UOM: boolean;
    HIDE_UOM_TO_BASE_RATIO: boolean;
    HIDE_UNIT_DISCOUNT_UOM_EXCL_TAX: boolean;
    HIDE_UNIT_PRICE_TXN_UOM_INCL_TAX: boolean;
    HIDE_AMOUNT_STD_EXCL_TAX: boolean;
    HIDE_DISCOUNT_AMOUNT_EXCL_TAX: boolean;
    HIDE_AMOUNT_NET_EXCL_TAX: boolean;
    HIDE_TAX_CONFIG_SELECTION: boolean;
    HIDE_WHT_CONFIG_SELECTION: boolean;
    HIDE_UNIT_PRICE_TXN: boolean;
    HIDE_AMOUNT_TXN: boolean;
    DISABLE_GEN_DOC_LISTING: boolean;

    HIDE_COSTING_DETAILS: boolean;
    HIDE_SERVER_DOC_1: boolean;
    HIDE_SERVER_DOC_2: boolean;
    HIDE_SERVER_DOC_3: boolean;
    HIDE_CLIENT_DOC_TYPE: boolean;
    HIDE_CLIENT_DOC_1: boolean;
    HIDE_CLIENT_DOC_2: boolean;
    HIDE_CLIENT_DOC_3: boolean;
    HIDE_CLIENT_DOC_4: boolean;
    HIDE_CLIENT_DOC_5: boolean;
    HIDE_REASON: boolean;
    MANDATORY_REASON_FIELD: boolean;
    MANDATORY_BIN_NUMBER: boolean;

    HIDE_CREDIT_TERMS:boolean;
    HIDE_CREDIT_LIMIT:boolean;
    HIDE_MEMBER_CARD:boolean;
    HIDE_DUE_DATE:boolean;
    HIDE_REMARKS:boolean;
    MANDATORY_REMARKS_FIELD:boolean;
    HIDE_REFERENCE:boolean;
    HIDE_CURRENCY:boolean;
    HIDE_BASE_CURRENCY:boolean;


    HIDE_GENDOC_VOID_BUTTON: boolean;
    HIDE_GENDOC_FINAL_BUTTON: boolean;
    HIDE_GENDOC_DISCARD_BUTTON: boolean;
    HIDE_GENDOC_SAVE_BUTTON: boolean;

    HIDE_ARAP_PNS: boolean;
    HIDE_ARAP_SETTLEMENT: boolean;
    HIDE_ARAP_DOC_OPEN: boolean;
    HIDE_ARAP_CONTRA: boolean;
    HIDE_ARAP_BAL: boolean;
    HIDE_DESCRIPTION: boolean;
    HIDE_LOCATION: boolean;
    HIDE_DELIVERY_BRANCH: boolean;
    HIDE_DELIVERY_LOCATION: boolean;
    ENABLE_BRANCH_FILTER: boolean;
    WORKFLOW_PROCESS_GUID: string;
    FINAL_STATUS_GUID: string;
    HIDE_DELIVERY_DETAILS_TAB: boolean;
    HIDE_MAIN_PAYMENT_TAB : boolean;
    HIDE_KO_FOR_TAB : boolean;
    HIDE_DEPARTMENT_HDR_TAB : boolean;
    HIDE_MAIN_ARAP_TAB : boolean;
    HIDE_TRACE_DOCUMENT_TAB: boolean;
    HIDE_MAIN_CONTRA_TAB : boolean;
    HIDE_DOC_LINK_TAB: boolean;
    HIDE_ATTACHMENT_TAB: boolean;
    HIDE_EXPORT_TAB: boolean;
    HIDE_SETTLEMENT_TAB: boolean;
    SORT_ORDER: string;
    ENABLE_FILTER_BY_TODAYS_TXN: boolean;
    salesManLabels: [];
    HIDE_SALES_AGENT: boolean;
    SALES_RETURN_WITH_PAYMENT: boolean;
    ENABLE_AUTO_POPUP: boolean;
    HIDE_CREATED_BY_DETAILS: boolean;

    HIDE_DOC_LINK: boolean;
    HIDE_RELATED_DOCUMENTS: boolean;
    HIDE_BIN_NUMBER: boolean;
    HIDE_BATCH_NUMBER: boolean;
    HIDE_CARD_NO: boolean;
    HIDE_NAME: boolean;
    HIDE_CARD_ISSUER: boolean;
    HIDE_CARD_EXPIRY: boolean;
    HIDE_APPROVAL_CODE: boolean;
    HIDE_BATCH: boolean;
    HIDE_CARD_TYPE: boolean;
    HIDE_CVV: boolean;
    MANDATORY_CARD_NO: boolean;
    MANDATORY_NAME: boolean;
    MANDATORY_CARD_ISSUER: boolean;
    MANDATORY_CARD_EXPIRY: boolean;
    MANDATORY_APPROVAL_CODE: boolean;
    MANDATORY_BATCH: boolean;
    MANDATORY_CARD_TYPE: boolean;
    MANDATORY_CVV: boolean;
    ENABLE_EDIT_SETTLEMENT_DATE: boolean;
    ENABLE_EDIT_PAYMENT_DATE: boolean;

    DEFAULT_POSTING_STATUS: string;
    WARN_EXCESS_RETURN_QUANTITY: boolean;
    ENABLE_EMPLOYEE_LOGIN_AUTO_DETECTION: boolean;
    ENABLE_ITEM_NAME_MAX_LIMIT: boolean;
    ITEM_NAME_MAX_LIMIT: number;

    VERTICAL_ORIENTATION: boolean;
    DEFAULT_ORIENTATION: string;

    SALES_RETURN_DETAILS_TAB_ORDER: { title: string; content: string; }[];

    EXPAND_MAIN_DETAILS: boolean;
    EXPAND_ACCOUNT: boolean;
    EXPAND_LINE_ITEMS: boolean;
    EXPAND_KO_FOR: boolean;
    EXPAND_DELIVERY_DETAILS: boolean;
    EXPAND_MAIN_ARAP: boolean;
    EXPAND_DEPARTMENT_HDR: boolean;
    EXPAND_TRACE_DOCUMENT: boolean;
    EXPAND_DOC_LINK: boolean;
    EXPAND_ATTACHMENT: boolean;
    EXPAND_EXPORT: boolean;
    EXPAND_MAIN_CONTRA: boolean;
    EXPAND_SETTLEMENT: boolean;
    EXPAND_POSTING: boolean;
    EXPAND_DELIVERY_TRIPS: boolean;
    SHOW_FOREX_DATA_SOURCE: boolean;
    CANNOT_EDIT_CURRENCY_RATE: boolean;
    HIDE_MAIN_DETAILS_SALES_AGENT: boolean;
    MANDATORY_MAIN_DETAILS_SALES_AGENT: boolean;
    HIDE_INTERCOMPANY_MENU: boolean;
    HIDE_FILE_EXPORT_MENU: boolean;
    HIDE_FILE_IMPORT_MENU: boolean;
    HIDE_FINAL_BUTTON: boolean;
    DEFAULT_TRANSACTION_DATE: boolean;
    ENABLE_EDITING_UNIT_PRICE_STD: boolean;
    HIDE_TOTAL_DISCOUNT_AMOUNT: boolean;
    ENABLE_EDIT_SETTLEMENT_FINAL: boolean;
}
